# Generated by Django 4.1.2 on 2022-10-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='document_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
